-- AlterTable
ALTER TABLE "wallets" ADD COLUMN     "expense" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "income" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "saving" DECIMAL(18,2) NOT NULL DEFAULT 0;
